# Generated by Django 3.1.1 on 2021-09-12 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Country",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255, unique=True)),
                ("name_native", models.CharField(max_length=255, unique=True)),
                ("iso2", models.CharField(max_length=2, unique=True)),
                ("iso3", models.CharField(max_length=3, unique=True)),
                ("population", models.IntegerField(blank=True, null=True)),
                ("latitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("longitude", models.DecimalField(decimal_places=6, max_digits=9)),
                ("is_un_member", models.BooleanField()),
                ("is_un_member_at", models.DateTimeField(blank=True, null=True)),
                ("flag", models.ImageField(upload_to="location/country/flag")),
            ],
            options={
                "verbose_name": "Country",
                "verbose_name_plural": "Countries",
                "unique_together": {("latitude", "longitude")},
            },
        ),
    ]
