# Generated by Django 3.1.1 on 2021-09-14 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("currency", "0001_initial"),
        ("location", "0002_populate_locations"),
    ]

    operations = [
        migrations.AddField(
            model_name="country",
            name="currency",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="countries",
                to="currency.currency",
            ),
        ),
    ]
