# Generated by Django 3.1.1 on 2021-09-14 07:31

# ┌─────────────────────────────────────────────────────────────────────────────────────
# │ GENERAL IMPORTS
# └─────────────────────────────────────────────────────────────────────────────────────

import os

# ┌─────────────────────────────────────────────────────────────────────────────────────
# │ DJANGO IMPORTS
# └─────────────────────────────────────────────────────────────────────────────────────

from django.db import migrations

# ┌─────────────────────────────────────────────────────────────────────────────────────
# │ PROJECT IMPORTS
# └─────────────────────────────────────────────────────────────────────────────────────

from tools import load_json


# ┌─────────────────────────────────────────────────────────────────────────────────────
# │ POPULATE CURRENCIES
# └─────────────────────────────────────────────────────────────────────────────────────


def populate_currencies(apps, schema_editor):
    """ Populates Currency model with currency fixtures """

    # ┌─────────────────────────────────────────────────────────────────────────────────
    # │ FIXTURES
    # └─────────────────────────────────────────────────────────────────────────────────

    # Define fixture path
    fixture_path = "currency/fixtures/"

    # Get currencies
    currencies = load_json(os.path.join(fixture_path, "currencies.json"))

    # Return if currencies is None
    if currencies is None:
        return

    # ┌─────────────────────────────────────────────────────────────────────────────────
    # │ COUNTRY
    # └─────────────────────────────────────────────────────────────────────────────────

    # Get Currency model
    Country = apps.get_model("location", "Country")

    # Get country ISO3 and primary keys
    countries = Country.objects.all().values_list("iso3", "pk")

    # Create a mapping if country primary keys by ISO3
    country_pks_by_iso3 = {iso3: pk for (iso3, pk) in countries}

    # ┌─────────────────────────────────────────────────────────────────────────────────
    # │ CURRENCY
    # └─────────────────────────────────────────────────────────────────────────────────

    # Get Currency model
    Currency = apps.get_model("currency", "Currency")

    # Define initialize currency helper
    def initialize_currency(currency):
        """ Returns a Currency object from a currency dict """

        # Get country primary key
        country_pk = country_pks_by_iso3.get(currency.pop("iso3"), None)

        # Set country primary key as ID
        currency["country_id"] = country_pk

        # Check if currency is Euro (need European Union flag)
        if currency["code"] == "EUR":

            # Add flag path to currency
            currency["flag"] = "location/country/flag/eu.png"

        # Initialize Currency instance
        currency = Currency(**currency)

        # Clean Currency instance
        currency.clean()

        # Return currency instance
        return currency

    # Bulk create currencies
    currencies = Currency.objects.bulk_create(
        [initialize_currency(currency) for currency in currencies]
    )


# ┌─────────────────────────────────────────────────────────────────────────────────────
# │ MIGRATION
# └─────────────────────────────────────────────────────────────────────────────────────


class Migration(migrations.Migration):
    """ Migration Class """

    # ┌─────────────────────────────────────────────────────────────────────────────────
    # │ CLASS ATTRIBUTES
    # └─────────────────────────────────────────────────────────────────────────────────

    dependencies = [
        ("currency", "0001_initial"),
    ]

    operations = [
        migrations.RunPython(populate_currencies),
    ]
